#!/bin/sh -e

# Check if port value is currently unset, and if so, set to 5000.
#
# The gadget snap may have set a value for the port, but if not, ensure it is
# set. Use port 5000 as a default value.

port="$(snapctl get port)"

# Initialize port to listen on
if [ -z "$port" ]; then
	snapctl set port=5000
fi
